SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE view [dbo].[v_SAP_voucher_detail]                       
(                        
voucher_num ,                        
voucher_status ,                        
voucher_type_code ,                        
voucher_cat_code ,                        
voucher_pay_recv_ind ,                        
cost_book_comp_num ,                        
cost_book_comp_short_name ,                        
cost_book_comp_full_name ,                        
acct_num ,                        
cpty_short_name ,                        
cpty_full_name ,                        
acct_instr_num ,                        
voucher_tot_amt ,                        
voucher_curr_code ,                        
voucher_credit_term_code ,                        
pay_method_code ,                        
voucher_pay_term_code ,                        
voucher_pay_days ,                        
voch_tot_paid_amt ,                        
voucher_creation_date ,                        
voucher_creator_init ,                        
voucher_auth_reqd_ind ,                        
voucher_auth_date ,                        
voucher_auth_init ,                        
voucher_eff_date ,                        
voucher_print_date ,                        
voucher_send_to_cust_date ,                        
voucher_book_date ,                        
voucher_mod_date ,                        
voucher_mod_init ,                        
voucher_writeoff_init ,                        
voucher_writeoff_date ,                        
voucher_cust_inv_amt ,                        
voucher_cust_inv_date ,                        
voucher_short_cmnt ,                        
cmnt_num ,                        
voucher_book_comp_num ,                        
voucher_book_curr_code ,                        
voucher_book_exch_rate ,                        
voucher_xrate_conv_ind ,                        
voucher_loi_num ,                        
voucher_arap_acct_code ,                        
voucher_send_to_arap_date ,                        
voucher_cust_ref_num ,                        
voucher_book_prd_date ,                        
voucher_paid_date ,                        
voucher_due_date ,                        
voucher_cash_date ,                        
voucher_trans_id ,                        
ref_voucher_num ,                        
custom_voucher_string ,                        
voucher_reversal_ind ,                        
voucher_hold_ind ,                        
max_line_num ,                        
bcomp_acct_bank_id,                        
bcomp_bank_name,                            
cpty_acct_bank_id,                        
cpty_bank_name,                           
voucher_inv_curr_code ,                        
voucher_inv_exch_rate ,                        
invoice_exch_rate_comment ,                        
cust_inv_recv_date ,                        
cust_inv_type_ind ,                        
special_bank_instr ,                        
revised_book_comp_bank_id ,                        
voucher_expected_pay_date ,                        
external_ref_key ,                        
cpty_inv_curr_code ,                        
voucher_full_cmnt ,                        
cost_num ,                        
cost_code ,                        
cost_status ,                        
cost_prim_sec_ind ,                        
cost_est_final_ind ,                        
cost_pay_rec_ind ,                        
cost_type_code ,                        
cost_owner_code ,                        
cost_owner_key1 ,                        
cost_owner_key2 ,                        
cost_owner_key3 ,                        
cost_owner_key4 ,                        
cost_owner_key5 ,                        
cost_owner_key6 ,                        
cost_owner_key7 ,                        
cost_owner_key8 ,                        
port_num ,                        
voucher_acct_num ,                        
cost_qty ,                        
cost_qty_uom_code ,                        
cost_qty_est_actual_ind ,                        
cost_unit_price ,                        
cost_price_curr_code ,                        
cost_price_uom_code ,                        
cost_price_est_actual_ind ,                        
cost_amt ,         
cost_amt_type ,                        
cost_vouchered_amt ,                        
cost_drawn_bal_amt ,                        
cost_pay_term_code ,                        
cost_pay_days ,       
cost_credit_term_code ,                        
cost_book_curr_code ,                        
cost_book_exch_rate ,                        
cost_xrate_conv_ind ,                        
creation_date ,                        
creator_init ,                        
cost_eff_date ,                        
cost_due_date ,                        
cost_due_date_mod_date ,                        
cost_due_date_mod_init ,                        
cost_gl_acct_cr_code ,                        
cost_gl_acct_dr_code ,                        
cost_gl_acct_mod_date ,                        
cost_gl_acct_mod_init ,                        
cost_gl_book_type_code ,                        
cost_gl_book_date ,                        
cost_gl_book_init ,                        
cost_gl_offset_acct_code ,                        
cost_short_cmnt ,                        
cost_price_mod_date ,                        
cost_price_mod_init ,                        
cost_pl_code ,                        
cost_paid_date ,                        
vc_acct_num ,                        
cost_cash_date ,                        
po_number ,                        
trans_id ,                        
finance_bank_num ,                        
del_term_code ,                        
alloc_num ,                        
alloc_item_num ,                        
actual_date ,                        
title_tran_date ,                        
disch_compl_date ,                        
trade_num ,                        
order_num ,                        
item_num ,                        
ProfitCntr ,                        
group_code ,                        
legal_entity_code ,                        
division_code ,                        
strategy_code ,                        
voyage_code ,                        
OrderType ,                        
mot_full_name ,                        
Location ,                        
exch_brkr_num ,                        
exch_brkr_name ,                        
contr_qty ,                        
port_full_name ,                        
load_port ,                        
discharge_port ,                        
Trader ,                        
cpty_bank_acct_num ,                        
cpty_addr_acct_num ,                        
cpty_addr_acct_addr_num ,                        
cpty_vc_acct_num ,                        
cpty_gl_acct_code ,                        
cpty_gl_acct_descr ,                        
cpty_p_or_r_ind ,                        
cpty_bank_acct_no ,                        
cpty_bank_addr ,                        
cpty_swift_code ,                        
cpty_pay_method_code ,                        
cpty_cost_send_id ,                        
cpty_acct_bank_routing_num ,                        
cpty_acct_bank_info_status ,                        
cpty_corresp_bank_name ,                        
cpty_corresp_bank_routing_num ,                        
cpty_further_credit_to ,                        
cpty_currency_code ,                        
cpty_corresp_swift_code ,                        
cpty_corresp_bank_acct_no ,                        
cpty_corresp_bank_instr_type_id ,                        
cpty_book_comp_num ,                        
cpty_further_credit_to_ext_acct_key ,                        
cpty_selling_office_num ,                        
cpty_bank_short_name ,                        
cpty_acct_bank_iban_num ,                        
cpty_acct_bank_city ,                        
cpty_cpty_acct_bank_country_code ,                        
cpty_corresp_bank_iban_num ,                        
cpty_corresp_bank_city ,                        
cpty_corresp_bank_country_code ,                        
cpty_special_payment_instr ,                        
bcomp_bank_acct_num ,                        
bcomp_addr_acct_num ,                        
bcomp_addr_acct_addr_num ,                        
bcomp_vc_acct_num ,                        
bcomp_gl_acct_code ,                        
bcomp_gl_acct_descr ,                        
bcomp_p_or_r_ind ,                        
bcomp_bank_acct_no ,                        
bcomp_bank_addr ,                        
bcomp_swift_code ,                        
bcomp_pay_method_code ,                        
bcomp_cost_send_id ,                        
bcomp_acct_bank_routing_num ,                        
bcomp_acct_bank_info_status ,                        
bcomp_corresp_bank_name ,                        
bcomp_corresp_bank_routing_num ,                   
bcomp_further_credit_to ,                        
bcomp_currency_code ,                        
bcomp_corresp_swift_code ,                        
bcomp_corresp_bank_acct_no ,                        
bcomp_corresp_bank_instr_type_id ,                        
bcomp_book_comp_num ,                        
bcomp_further_credit_to_ext_acct_key ,                        
bcomp_selling_office_num ,                        
bcomp_bank_short_name ,                   
bcomp_acct_bank_iban_num ,                        
bcomp_acct_bank_city ,                        
bcomp_bcomp_acct_bank_country_code ,                        
bcomp_corresp_bank_iban_num ,                        
bcomp_corresp_bank_city ,                        
bcomp_corresp_bank_country_code ,                        
bcomp_special_payment_instr   ,                      
SAPReference,                      
SAPReference2,                      
VatInfo  ,                    
aiastring  ,                  
credit_note_ind              
)                        
AS                        
                        
SELECT                        
v.voucher_num,                        
v.voucher_status,                        
v.voucher_type_code,                        
v.voucher_cat_code,                        
v.voucher_pay_recv_ind,                        
c.cost_book_comp_num,                              
ba.acct_short_name as cost_book_comp_short_name,                              
ba.acct_full_name as cost_book_comp_full_name,                        
v.acct_num,                        
ca.acct_short_name as cpty_short_name,                               
ca.acct_full_name as cpty_full_name,                        
v.acct_instr_num,                        
v.voucher_tot_amt,                        
isnull(cmdty.cmdty_short_name,v.voucher_curr_code) voucher_curr_code ,                        
v.credit_term_code,                        
v.pay_method_code,                        
v.pay_term_code,                        
v.voucher_pay_days,                        
v.voch_tot_paid_amt,                        
v.voucher_creation_date,                        
v.voucher_creator_init,                        
v.voucher_auth_reqd_ind,                        
v.voucher_auth_date,                        
v.voucher_auth_init,                        
v.voucher_eff_date,                        
v.voucher_print_date,                        
v.voucher_send_to_cust_date,                        
v.voucher_book_date,                        
v.voucher_mod_date,                        
v.voucher_mod_init,                        
v.voucher_writeoff_init,                        
v.voucher_writeoff_date,                        
v.voucher_cust_inv_amt,                        
v.voucher_cust_inv_date,                        
v.voucher_short_cmnt,                        
v.cmnt_num,                        
v.voucher_book_comp_num,                        
isnull(bcurr.cmdty_short_name,v.voucher_book_curr_code) voucher_book_curr_code,                        
v.voucher_book_exch_rate,                        
v.voucher_xrate_conv_ind,                        
v.voucher_loi_num,                        
v.voucher_arap_acct_code,                        
v.voucher_send_to_arap_date,     
v.voucher_cust_ref_num,                        
v.voucher_book_prd_date,                        
v.voucher_paid_date,                        
v.voucher_due_date,                        
--v.voucher_acct_name,                        
--v.voucher_book_comp_name,                        
v.cash_date,                        
v.trans_id voucher_trans_id,                        
v.ref_voucher_num,                        
v.custom_voucher_string,                        
v.voucher_reversal_ind,                        
v.voucher_hold_ind,                        
v.max_line_num,                        
v.book_comp_acct_bank_id bcomp_acct_bank_id,                        
bcomp.bank_name bcomp_bank_name,                            
v.cp_acct_bank_id cpty_acct_bank_id,                        
cpty.bank_name cpty_bank_name,                           
isnull(icurr.cmdty_short_name,v.voucher_inv_curr_code) voucher_inv_curr_code,                        
v.voucher_inv_exch_rate,                        
v.invoice_exch_rate_comment,                        
v.cust_inv_recv_date,                        
v.cust_inv_type_ind,                        
v.special_bank_instr,                        
v.revised_book_comp_bank_id,                        
v.voucher_expected_pay_date,                        
v.external_ref_key,                        
isnull(cpcurr.cmdty_short_name,v.cpty_inv_curr_code) cpty_inv_curr_code,                        
convert(nvarchar(MAX),isnull(vcmnt.cmnt_text,isnull(vcmnt.short_cmnt,vcmnt.tiny_cmnt))) voucher_full_cmnt,                         
c.cost_num,                              
c.cost_code,                
--CASE WHEN c.cost_type_code in ('CPP','CPR') then isnull(ccurr.cmdty_short_name,c.cost_code) else c.cost_code end cost_code,                              
c.cost_status,                              
c.cost_prim_sec_ind,                              
c.cost_est_final_ind,                              
c.cost_pay_rec_ind,                              
c.cost_type_code,                              
c.cost_owner_code,                              
c.cost_owner_key1,                              
c.cost_owner_key2,                              
c.cost_owner_key3,                              
c.cost_owner_key4,                              
c.cost_owner_key5,                              
c.cost_owner_key6,                              
c.cost_owner_key7,                              
c.cost_owner_key8,                              
c.port_num,                              
c.acct_num,                              
c.cost_qty,                              
c.cost_qty_uom_code,                              
c.cost_qty_est_actual_ind,                              
c.cost_unit_price,                              
isnull(ccurr.cmdty_short_name,c.cost_price_curr_code) cost_price_curr_code,                              
c.cost_price_uom_code,                              
c.cost_price_est_actual_ind,                         
c.cost_amt,                              
c.cost_amt_type,                              
c.cost_vouchered_amt,                              
c.cost_drawn_bal_amt,                              
c.pay_term_code,                              
c.cost_pay_days,                              
c.credit_term_code,                              
isnull(bcurr.cmdty_short_name,c.cost_book_curr_code) cost_book_curr_code,                              
c.cost_book_exch_rate,                              
c.cost_xrate_conv_ind,                              
c.creation_date,                              
c.creator_init,                              
c.cost_eff_date,                              
c.cost_due_date,                              
c.cost_due_date_mod_date,                              
c.cost_due_date_mod_init,                              
c.cost_gl_acct_cr_code,                              
c.cost_gl_acct_dr_code,                              
c.cost_gl_acct_mod_date,                              
c.cost_gl_acct_mod_init,                              
c.cost_gl_book_type_code,                            
c.cost_gl_book_date,                              
c.cost_gl_book_init,                              
c.cost_gl_offset_acct_code,                             
c.cost_short_cmnt,                  c.cost_price_mod_date,                              
c.cost_price_mod_init,                              
c.cost_pl_code,                              
c.cost_paid_date,                              
c.vc_acct_num,                              
c.cash_date,                              
c.po_number,                              
c.trans_id,                              
c.finance_bank_num,                              
tiwp.del_term_code,                              
tiwp.alloc_num,                         
tiwp.alloc_item_num,                              
ai_est_actual_date actual_date,                              
title_tran_date,                              
disch_compl_date,                              
tiwp.trade_num,                              
tiwp.order_num,                              
tiwp.item_num,                               
profit_center_code as ProfitCntr,                         
group_code ,                        
legal_entity_code,                         
division_code,                        
strategy_code,                              
cei.voyage_code,                               
tro.order_type_code as OrderType,                              
isnull(tiwp.mot_full_name,tiwp1.mot_full_name) 'mot_full_name',                              
isnull(tiwp.loc_name,tiwp1.loc_name) as Location,                              
ti.exch_brkr_num,                              
ti.exch_brkr_name,                        
contr_qty,                              
p.port_full_name,                              
load_port,                              
discharge_port,                              
iu.user_first_name +' ' +iu.user_last_name 'Trader' ,                               
cpty.bank_acct_num cpty_bank_acct_num ,                        
cpty.addr_acct_num cpty_addr_acct_num ,                        
cpty.addr_acct_addr_num cpty_addr_acct_addr_num ,                        
cpty.vc_acct_num cpty_vc_acct_num ,                        
cpty.gl_acct_code cpty_gl_acct_code ,                        
cpty.gl_acct_descr cpty_gl_acct_descr ,         
cpty.p_or_r_ind cpty_p_or_r_ind ,                        
cpty.bank_acct_no cpty_bank_acct_no ,                        
cpty.bank_addr cpty_bank_addr ,                        
cpty.swift_code cpty_swift_code ,                        
cpty.pay_method_code cpty_pay_method_code ,                        
cpty.cost_send_id cpty_cost_send_id ,                        
cpty.acct_bank_routing_num cpty_acct_bank_routing_num ,                        
cpty.acct_bank_info_status cpty_acct_bank_info_status ,                        
cpty.corresp_bank_name cpty_corresp_bank_name ,                        
cpty.corresp_bank_routing_num cpty_corresp_bank_routing_num ,                        
cpty.further_credit_to cpty_further_credit_to ,                        
isnull(cpbcurr.cmdty_short_name, cpty.currency_code) cpty_currency_code ,                        
cpty.corresp_swift_code cpty_corresp_swift_code ,                        
cpty.corresp_bank_acct_no cpty_corresp_bank_acct_no ,                        
cpty.corresp_bank_instr_type_id cpty_corresp_bank_instr_type_id ,                        
cpty.book_comp_num cpty_book_comp_num ,                        
cpty.further_credit_to_ext_acct_key cpty_further_credit_to_ext_acct_key ,                        
cpty.selling_office_num cpty_selling_office_num ,                        
cpty.bank_short_name cpty_bank_short_name ,                        
cpty.acct_bank_iban_num cpty_acct_bank_iban_num ,                        
cpty.acct_bank_city cpty_acct_bank_city ,                        
cpty.acct_bank_country_code cpty_cpty_acct_bank_country_code ,                        
cpty.corresp_bank_iban_num cpty_corresp_bank_iban_num ,                        
cpty.corresp_bank_city cpty_corresp_bank_city ,                        
cpty.corresp_bank_country_code cpty_corresp_bank_country_code ,                        
cpty.special_payment_instr cpty_special_payment_instr ,                        
bcomp.bank_acct_num bcomp_bank_acct_num ,                        
bcomp.addr_acct_num bcomp_addr_acct_num ,                        
bcomp.addr_acct_addr_num bcomp_addr_acct_addr_num ,                        
bcomp.vc_acct_num bcomp_vc_acct_num ,                        
bcomp.gl_acct_code bcomp_gl_acct_code ,                        
bcomp.gl_acct_descr bcomp_gl_acct_descr ,                        
bcomp.p_or_r_ind bcomp_p_or_r_ind ,                        
bcomp.bank_acct_no bcomp_bank_acct_no ,                        
bcomp.bank_addr bcomp_bank_addr ,                        
bcomp.swift_code bcomp_swift_code ,                        
bcomp.pay_method_code bcomp_pay_method_code ,                        
bcomp.cost_send_id bcomp_cost_send_id ,                        
bcomp.acct_bank_routing_num bcomp_acct_bank_routing_num ,                        
bcomp.acct_bank_info_status bcomp_acct_bank_info_status ,                        
bcomp.corresp_bank_name bcomp_corresp_bank_name ,                        
bcomp.corresp_bank_routing_num bcomp_corresp_bank_routing_num ,                        
bcomp.further_credit_to bcomp_further_credit_to ,                        
isnull(bccurr.cmdty_short_name,bcomp.currency_code) bcomp_currency_code ,                        
bcomp.corresp_swift_code bcomp_corresp_swift_code ,                        
bcomp.corresp_bank_acct_no bcomp_corresp_bank_acct_no ,                        
bcomp.corresp_bank_instr_type_id bcomp_corresp_bank_instr_type_id ,                        
bcomp.book_comp_num bcomp_book_comp_num ,                        
bcomp.further_credit_to_ext_acct_key bcomp_further_credit_to_ext_acct_key ,                        
bcomp.selling_office_num bcomp_selling_office_num ,                        
bcomp.bank_short_name bcomp_bank_short_name ,                        
bcomp.acct_bank_iban_num bcomp_acct_bank_iban_num ,                        
bcomp.acct_bank_city bcomp_acct_bank_city ,                  
bcomp.acct_bank_country_code bcomp_bcomp_acct_bank_country_code ,                        
bcomp.corresp_bank_iban_num bcomp_corresp_bank_iban_num ,                        
bcomp.corresp_bank_city bcomp_corresp_bank_city ,                        
bcomp.corresp_bank_country_code bcomp_corresp_bank_country_code ,                        
bcomp.special_payment_instr bcomp_special_payment_instr   ,                      
sapref.target_key1 SAPReference,                      
sapref2.target_key1 SAPReference2,                      
substring (ccmnt.short_cmnt , charindex('<TEXTID>',ccmnt.short_cmnt )+8,charindex('</TEXTID>',substring (ccmnt.short_cmnt , charindex('<TEXTID>',ccmnt.short_cmnt )+8,25))-1) 'VatID'  ,                    
CASE                     
 WHEN c.cost_owner_code in ('A','AI','AA')                     
  THEN convert(varchar,c.cost_owner_key1)+'/'+convert(varchar,c.cost_owner_key2)+'/'+convert(varchar,c.cost_owner_key3)                    
 WHEN c.cost_type_code in ('PR','PO')                    
  THEN convert(varchar,ais.cost_owner_key1)+'/'+convert(varchar,ais.cost_owner_key2)+'/'+convert(varchar,ais.cost_owner_key3)                    
END 'aiastring'      ,               
vei.custom_field2 'pr_for_booking'                    
from cost c  WITH (NOLOCK)         
 left join commodity ccurr  WITH (NOLOCK) ON ccurr.cmdty_code=c.cost_price_curr_code                           
 left join ( select ti1.trade_num, ti1.order_num,ti1.item_num,ti1.exch_brkr_num, be.acct_short_name 'exch_brkr_name',contr_qty                              
    from trade_item ti1 WITH (NOLOCK)                          
   LEFT OUTER JOIN account be WITH (NOLOCK) ON ti1.exch_brkr_num=be.acct_num)                             
   ti on c.cost_owner_key6 = ti.trade_num and c.cost_owner_key7 = ti.order_num and c.cost_owner_key8 = ti.item_num                                left join (                              
    select distinct ai.alloc_num,ai.alloc_item_num,ai_est_actual_num,mot_full_name,ai_est_actual_date,trade_num,                   
  order_num, item_num,title_tran_loc_code,title_tran_date,origin_loc_code, dest_loc_code, del_term_code,nor_date,bl_date,                   
  l.loc_name, disch_compl_date, ld.loc_name 'load_port', dis.loc_name 'discharge_port'                              
    from allocation_item ai WITH (NOLOCK)                              
    LEFT OUTER JOIN allocation_item_transport ait WITH (NOLOCK) ON ai.alloc_num=ait.alloc_num and ai.alloc_item_num=ait.alloc_item_num                              
    LEFT OUTER JOIN mot m WITH (NOLOCK) ON ait.transportation=m.mot_code                              
    LEFT OUTER JOIN location l WITH (NOLOCK) ON title_tran_loc_code = l.loc_code                              
    LEFT OUTER JOIN ai_est_actual aia WITH (NOLOCK) ON aia.alloc_num=ai.alloc_num  and aia.alloc_item_num=ai.alloc_item_num and aia.ai_est_actual_num<>0                              
    LEFT OUTER JOIN location ld WITH (NOLOCK) ON ld.loc_code=ai.load_port_loc_code                              
    LEFT OUTER JOIN location dis WITH (NOLOCK) ON dis.loc_code=ai.final_dest_loc_code                              
   ) tiwp on c.cost_owner_key6 = tiwp.trade_num and c.cost_owner_key7 = tiwp.order_num                   
 and c.cost_owner_key8 = tiwp.item_num and tiwp.alloc_num=c.cost_owner_key1 and tiwp.alloc_item_num=c.cost_owner_key2                     
 and ISNULL(tiwp.ai_est_actual_num,0)=ISNULL(c.cost_owner_key3,0)                          
 left join (                               
    select distinct trade_num, order_num, item_num,del_loc_code,del_term_code,mot_full_name,l.loc_name                              
    from trade_item_wet_phy wet WITH (NOLOCK) , mot m WITH (NOLOCK) , location l WITH (NOLOCK)                              
    where del_loc_code = l.loc_code                              
    and wet.mot_code=m.mot_code                              
   ) tiwp1 on c.cost_owner_key6 = tiwp1.trade_num and c.cost_owner_key7 = tiwp1.order_num and c.cost_owner_key8 = tiwp1.item_num                               
 left join trade_order tro WITH (NOLOCK) on ti.trade_num = tro.trade_num and ti.order_num = tro.order_num                              
 left join trade t WITH (NOLOCK) on ti.trade_num = t.trade_num                               
 left join icts_user iu WITH (NOLOCK) on iu.user_init=t.trader_init                              
 left join voucher_cost vc WITH (NOLOCK) ON c.cost_num = vc.cost_num                              
 left join voucher v WITH (NOLOCK) ON vc.voucher_num=v.voucher_num                   
 left join voucher_ext_info vei WITH (NOLOCK) ON vei.voucher_num=v.voucher_num                    
 left join account ca WITH (NOLOCK) on isnull(v.acct_num,c.acct_num) = ca.acct_num                              
 left join account ba WITH (NOLOCK) on c.cost_book_comp_num = ba.acct_num                              
 left join account fa WITH (NOLOCK) on c.finance_bank_num = fa.acct_num                              
 left join commodity icurr WITH (NOLOCK) ON icurr.cmdty_code=voucher_inv_curr_code                  
 left join commodity bcurr WITH (NOLOCK) ON bcurr.cmdty_code=voucher_book_curr_code                  
 left join commodity cmdty WITH (NOLOCK) ON v.voucher_curr_code=cmdty.cmdty_code                  
 left join commodity cpcurr WITH (NOLOCK) ON cpcurr.cmdty_code=v.cpty_inv_curr_code                  
 --left join voucher_payment vp ON v.voucher_num=vp.voucher_num                              
 left outer join dbo.account_bank_info cpty WITH (NOLOCK) on cpty.acct_bank_id = cp_acct_bank_id                              
 left outer join commodity cpbcurr WITH (NOLOCK) ON cpbcurr.cmdty_code=cpty.currency_code                  
 left outer join dbo.account_bank_info bcomp WITH (NOLOCK) on bcomp.acct_bank_id = book_comp_acct_bank_id                              
 left outer join commodity bccurr WITH (NOLOCK) ON bccurr.cmdty_code=bcomp.currency_code                  
 left outer join comment vcmnt WITH (NOLOCK) ON vcmnt.cmnt_num=v.cmnt_num                              
 left outer join comment ccmnt WITH (NOLOCK) ON ccmnt.cmnt_num=c.cmnt_num        
 left join cost_ext_info cei WITH (NOLOCK) on c.cost_num = cei.cost_num                              
 left join portfolio p WITH (NOLOCK) on c.port_num = p.port_num                              
 left join jms_reports jr WITH (NOLOCK) on c.port_num = jr.port_num                              
 left outer join assign_trade at WITH (NOLOCK) on c.cost_owner_key6=at.trade_num and c.cost_owner_key7=at.order_num and c.cost_owner_key8=at.item_num                               
   and c.cost_owner_key1=at.alloc_num and c.cost_owner_key2=at.alloc_item_num                              
left outer join lc l WITH (NOLOCK) on at.ct_doc_num=l.lc_num                              
left join icts_user ciu WITH (NOLOCK) on ciu.user_init=l.lc_cr_analyst_init                              
left join account lib WITH (NOLOCK) on l.lc_issuing_bank = lib.acct_num                           
left join entity_tag sapref WITH (NOLOCK) ON sapref.entity_tag_id=79 and sapref.key1=v.voucher_num                      
left join entity_tag sapref2 WITH (NOLOCK) ON sapref2.entity_tag_id=76 and sapref2.key1=v.voucher_num                      
left join cost ais WITH (NOLOCK) ON c.cost_type_code in ('PR','PO') and c.cost_owner_key1=ais.cost_num and ais.cost_owner_code in ('A','AI','AA')                    
where c.cost_status != 'CLOSED'                               
        
union        
      
SELECT      
voucher_num ,                    
'C' ,                    
voucher_type_code ,                    
voucher_cat_code ,                    
voucher_pay_recv_ind ,                    
NULL ,                    
NULL ,                    
NULL ,                    
acct_num ,                    
NULL ,                    
NULL ,                    
acct_instr_num ,                    
voucher_tot_amt ,                    
voucher_curr_code ,                    
credit_term_code ,                    
pay_method_code ,                    
pay_term_code ,                    
voucher_pay_days ,                    
voch_tot_paid_amt ,                    
voucher_creation_date ,                    
voucher_creator_init ,                    
voucher_auth_reqd_ind ,                    
voucher_auth_date ,                    
voucher_auth_init ,                    
voucher_eff_date ,                    
voucher_print_date ,                    
voucher_send_to_cust_date ,                    
voucher_book_date ,                    
voucher_mod_date ,                    
voucher_mod_init ,                    
voucher_writeoff_init ,                    
voucher_writeoff_date ,                    
voucher_cust_inv_amt ,                    
voucher_cust_inv_date ,                    
NULL ,                    
cmnt_num ,                    
voucher_book_comp_num ,                    
voucher_book_curr_code ,                    
voucher_book_exch_rate ,                    
voucher_xrate_conv_ind ,                    
voucher_loi_num ,                    
voucher_arap_acct_code ,                    
voucher_send_to_arap_date ,                    
voucher_cust_ref_num ,                    
voucher_book_prd_date ,                    
voucher_paid_date ,                    
voucher_due_date ,                    
cash_date ,                    
trans_id ,                    
ref_voucher_num ,                    
custom_voucher_string ,                    
voucher_reversal_ind ,                    
voucher_hold_ind ,                    
max_line_num ,                    
NULL,                    
NULL,                        
NULL,                    
NULL,                       
voucher_inv_curr_code ,                    
voucher_inv_exch_rate ,                    
invoice_exch_rate_comment ,                    
cust_inv_recv_date ,                    
cust_inv_type_ind ,                    
special_bank_instr ,                    
revised_book_comp_bank_id ,                    
voucher_expected_pay_date ,                    
external_ref_key ,                    
cpty_inv_curr_code ,                    
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL      
from voucher v       
where not exists (select 1 from voucher_cost vc where v.voucher_num=vc.voucher_num)      
--and exists (select 1 from aud_voucher where voucher_book_date is not null)      
      
union      
SELECT      
voucher_num ,                    
'C' ,                    
voucher_type_code ,                    
voucher_cat_code ,                    
voucher_pay_recv_ind ,                    
NULL ,                    
NULL ,                    
NULL ,                    
acct_num ,                    
NULL ,                    
NULL ,                    
acct_instr_num ,                    
voucher_tot_amt ,                    
voucher_curr_code ,                    
credit_term_code ,                    
pay_method_code ,                    
pay_term_code ,                    
voucher_pay_days ,                    
voch_tot_paid_amt ,                    
voucher_creation_date ,                    
voucher_creator_init ,                    
voucher_auth_reqd_ind ,                    
voucher_auth_date ,                    
voucher_auth_init ,                    
voucher_eff_date ,                    
voucher_print_date ,                    
voucher_send_to_cust_date ,                    
voucher_book_date ,                    
voucher_mod_date ,                    
voucher_mod_init ,                    
voucher_writeoff_init ,                    
voucher_writeoff_date ,                    
voucher_cust_inv_amt ,                    
voucher_cust_inv_date ,                    
NULL ,                    
cmnt_num ,                    
voucher_book_comp_num ,                    
voucher_book_curr_code ,                    
voucher_book_exch_rate ,                    
voucher_xrate_conv_ind ,                    
voucher_loi_num ,                    
voucher_arap_acct_code ,                    
voucher_send_to_arap_date ,                    
voucher_cust_ref_num ,                    
voucher_book_prd_date ,                    
voucher_paid_date ,                    
voucher_due_date ,                    
cash_date ,                    
trans_id ,                    
ref_voucher_num ,                    
custom_voucher_string ,                    
voucher_reversal_ind ,                    
voucher_hold_ind ,                    
max_line_num ,                    
NULL,                    
NULL,                        
NULL,                    
NULL,                       
voucher_inv_curr_code ,                    
voucher_inv_exch_rate ,                    
invoice_exch_rate_comment ,                    
cust_inv_recv_date ,                    
cust_inv_type_ind ,                    
special_bank_instr ,                    
revised_book_comp_bank_id ,                    
voucher_expected_pay_date ,                    
external_ref_key ,                    
cpty_inv_curr_code ,                    
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL      
from voucher v       
where not exists (select 1 from voucher_cost vc where v.voucher_num=vc.voucher_num)      
--and exists (select 1 from aud_voucher where voucher_book_date is not null)      
      
union      
SELECT      
voucher_num ,                    
'D' ,             
NULL  ,                    
NULL  ,                    
NULL  ,                    
NULL ,                    
NULL ,                    
NULL ,                    
NULL  ,                    
NULL ,                    
NULL ,                    
NULL  ,                    
NULL  ,                    
NULL  ,                    
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
max(voucher_mod_date) ,                    
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
max(resp_trans_id) ,                    
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL,      
NULL      
from aud_voucher av        
where not exists (select 1 from voucher v where av.voucher_num=v.voucher_num)            
group by av.voucher_num      
GO
GRANT SELECT ON  [dbo].[v_SAP_voucher_detail] TO [next_usr]
GO
