SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

CREATE view [dbo].[v_trade_item_dist_rev]
(
   dist_num,
   trade_num,
   order_num,
   item_num,
   accum_num,
   qpp_num,
   pos_num,
   real_port_num,
   dist_type,
   real_synth_ind,
   is_equiv_ind,
   what_if_ind,
   bus_date,
   p_s_ind,
   dist_qty,
   alloc_qty,
   discount_qty,
   priced_qty,
   qty_uom_code,
   qty_uom_code_conv_to,
   qty_uom_conv_rate,
   price_curr_code_conv_to,
   price_curr_conv_rate,
   price_uom_code_conv_to,
   price_uom_conv_rate,
   spread_pos_group_num,
   delivered_qty,
   open_pl,
   pl_asof_date,
   closed_pl,
   addl_cost_sum,
   sec_conversion_factor,
   sec_qty_uom_code,
   commkt_key,
   trading_prd,
   estimate_qty,
   formula_num,
   formula_body_num,
   trans_id,
   asof_trans_id,
   resp_trans_id
)
as
select
   dist_num,
   trade_num,
   order_num,
   item_num,
   accum_num,
   qpp_num,
   pos_num,
   real_port_num,
   dist_type,
   real_synth_ind,
   is_equiv_ind,
   what_if_ind,
   bus_date,
   p_s_ind,
   dist_qty,
   alloc_qty,
   discount_qty,
   priced_qty,
   qty_uom_code,
   qty_uom_code_conv_to,
   qty_uom_conv_rate,
   price_curr_code_conv_to,
   price_curr_conv_rate,
   price_uom_code_conv_to,
   price_uom_conv_rate,
   spread_pos_group_num,
   delivered_qty,
   open_pl,
   pl_asof_date,
   closed_pl,
   addl_cost_sum,
   sec_conversion_factor,
   sec_qty_uom_code,
   commkt_key,
   trading_prd,
   estimate_qty,
   formula_num,
   formula_body_num,
   trans_id,
   trans_id,
   resp_trans_id
from dbo.aud_trade_item_dist                                                                                                                                                                                                                                                
GO
GRANT SELECT ON  [dbo].[v_trade_item_dist_rev] TO [admin_group]
GO
GRANT SELECT ON  [dbo].[v_trade_item_dist_rev] TO [next_usr]
GO
EXEC sp_addextendedproperty N'SymphonyProduct', N'OIL', 'SCHEMA', N'dbo', 'VIEW', N'v_trade_item_dist_rev', NULL, NULL
GO
