SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

CREATE view [dbo].[v_shipment_rev]
(
   oid,
   status,
   reference,
   primary_shipment_num,
   alloc_num,
   mot_type_code,
   capacity,
   capacity_uom_code,
   ship_qty,
   ship_qty_uom_code,
   cmdty_code,
   start_loc_code,
   end_loc_code,
   start_date,
   end_date,
   transport_owner_id,
   transport_operator_id,
   pipeline_cycle_num,
   freight_rate,
   freight_rate_uom_code,
   freight_rate_curr_code,
   freight_pay_term_code,
   contract_num,
   creator_init,
   creation_date,
   last_update_by_init,
   last_update_date,
   trans_id,
   asof_trans_id,
   resp_trans_id,
   transport_reference,
   cmnt_num,
   load_facility_code,
   load_tank_num,
   dest_facility_code,
   dest_tank_num,
   contract_order_num,
   manual_transport_parcels,
   feed_interface,
   balance_qty,
   sap_shipment_num
)
as
select
   oid,
   status,
   reference,
   primary_shipment_num,
   alloc_num,
   mot_type_code,
   capacity,
   capacity_uom_code,
   ship_qty,
   ship_qty_uom_code,
   cmdty_code,
   start_loc_code,
   end_loc_code,
   start_date,
   end_date,
   transport_owner_id,
   transport_operator_id,
   pipeline_cycle_num,
   freight_rate,
   freight_rate_uom_code,
   freight_rate_curr_code,
   freight_pay_term_code,
   contract_num,
   creator_init,
   creation_date,
   last_update_by_init,
   last_update_date,
   trans_id,
   trans_id,
   resp_trans_id,
   transport_reference,
   cmnt_num,
   load_facility_code,
   load_tank_num,
   dest_facility_code,
   dest_tank_num,
   contract_order_num,
   manual_transport_parcels,
   feed_interface,
   balance_qty,
   sap_shipment_num
from dbo.aud_shipment
GO
GRANT SELECT ON  [dbo].[v_shipment_rev] TO [admin_group]
GO
GRANT SELECT ON  [dbo].[v_shipment_rev] TO [next_usr]
GO
EXEC sp_addextendedproperty N'SymphonyProduct', N'OIL', 'SCHEMA', N'dbo', 'VIEW', N'v_shipment_rev', NULL, NULL
GO
