SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

CREATE procedure [dbo].[fetchTradeItemRevPK]
   @asof_trans_id   bigint,
   @item_num        smallint,
   @order_num       smallint,
   @trade_num       int
as
declare @trans_id   bigint

   select @trans_id = trans_id
   from dbo.trade_item
   where trade_num = @trade_num and
         order_num = @order_num and
         item_num = @item_num

if @trans_id <= @asof_trans_id
begin
   select
       accum_periodicity,
       active_status_ind,
       -- addl_cost_sum,
       agreement_num,
       amend_creation_date,
       amend_effect_end_date,
       amend_effect_start_date,
       amend_num,
       asof_trans_id=@asof_trans_id,
       avg_price,
       b2b_trade_item,
       billing_type,
       booking_comp_num,
       brkr_comm_amt,
       brkr_comm_curr_code,
       brkr_comm_uom_code,
       brkr_cont_num,
       brkr_num,
       brkr_ref_num,
       calendar_code,
       clr_service_num,
       cmdty_code,
       cmnt_num,
       committed_qty_uom_code,
       -- contr_mtm_pl,
       contr_qty,
       contr_qty_periodicity,
       contr_qty_uom_code,
       disch_port_loc_code,
       estimate_ind,
       exch_brkr_num,
       excp_addns_code,
       finance_bank_num,
	   flat_amt,
       formula_declar_date,
       formula_ind,
       fut_trader_init,
       gtc_code,
       hedge_curr_code,
       hedge_multi_div_ind,
       hedge_pos_ind,
       hedge_rate,
       idms_acct_alloc,
       idms_bb_ref_num,
       idms_contr_num,
       idms_profit_center,
       includes_excise_tax_ind,  
       includes_fuel_tax_ind,
       internal_parent_item_num,
       internal_parent_order_num,
       internal_parent_trade_num,
       is_cleared_ind,
       is_lc_assigned,
       is_rc_assigned,
       item_confirm_ind,
       item_num,
       item_status_code,
       item_type,
	   leg_id,
       load_port_loc_code,
       market_value,
       max_accum_num,
       -- mtm_pl,
       -- mtm_pl_as_of_date,
       -- mtm_pl_curr_code,
       open_qty,
       open_qty_uom_code,
       order_num,
       origin_country_code,
       p_s_ind,
       parent_item_num,
       pooling_port_ind,
       pooling_port_num,
       pooling_type,
       price_curr_code,
       price_uom_code,
       priced_qty_uom_code,
       purchasing_group,
       quote_id,
		real_port_num,
		real_quote_period_id,
       recap_item_num,
       resp_trans_id = null,
       rin_ind,    
       risk_mkt_code,
       sap_order_num,
       sch_qty_uom_code,
       sched_status,
       strip_item_status,
       summary_item_num,
       title_mkt_code, 
       total_committed_qty,
       total_priced_qty,
       total_sch_qty,
       trade_modified_ind,
       trade_num,
       trading_prd,
       trans_id,
       uom_conv_rate,
       use_mkt_formula_for_pl
   from dbo.trade_item
   where trade_num = @trade_num and
         order_num = @order_num and
         item_num = @item_num
end
else
begin
   set rowcount 1
   select 
       accum_periodicity,
       active_status_ind,
       -- addl_cost_sum,
       agreement_num,
       amend_creation_date,
       amend_effect_end_date,
       amend_effect_start_date,
       amend_num,
       asof_trans_id=@asof_trans_id,
       avg_price,
       b2b_trade_item,
       billing_type,
       booking_comp_num,
       brkr_comm_amt,
       brkr_comm_curr_code,
       brkr_comm_uom_code,
       brkr_cont_num,
       brkr_num,
       brkr_ref_num,
       calendar_code,
       clr_service_num,
       cmdty_code,
       cmnt_num,   
       committed_qty_uom_code,
       -- contr_mtm_pl,
       contr_qty,
       contr_qty_periodicity,
       contr_qty_uom_code,
       disch_port_loc_code,
       estimate_ind,
       exch_brkr_num,
       excp_addns_code,
       finance_bank_num,
	   flat_amt,	   
       formula_declar_date,
       formula_ind,
       fut_trader_init,
       gtc_code,
       hedge_curr_code,
       hedge_multi_div_ind,
       hedge_pos_ind,
       hedge_rate,
       idms_acct_alloc,
       idms_bb_ref_num,
       idms_contr_num,
       idms_profit_center,
       includes_excise_tax_ind,  
       includes_fuel_tax_ind,
       internal_parent_item_num,
       internal_parent_order_num,
       internal_parent_trade_num,
       is_cleared_ind,
       is_lc_assigned,
       is_rc_assigned,
       item_confirm_ind,
       item_num,
       item_status_code,
       item_type,
	   leg_id,
       load_port_loc_code,
       market_value,
       max_accum_num,
       -- mtm_pl,
       -- mtm_pl_as_of_date,
       -- mtm_pl_curr_code,
       open_qty,
       open_qty_uom_code,
       order_num,
       origin_country_code,
       p_s_ind,
       parent_item_num,
       pooling_port_ind,
       pooling_port_num,
       pooling_type,
       price_curr_code,
       price_uom_code,
       priced_qty_uom_code,
       purchasing_group,
       quote_id,
		real_port_num,
		real_quote_period_id,
       recap_item_num,
       resp_trans_id,
       rin_ind,    
       risk_mkt_code,
       sap_order_num,
       sch_qty_uom_code,
       sched_status,
       strip_item_status,
       summary_item_num,
       title_mkt_code,   
       total_committed_qty,
       total_priced_qty,
       total_sch_qty,
       trade_modified_ind,
       trade_num,
       trading_prd,
       trans_id,
       uom_conv_rate,
       use_mkt_formula_for_pl
   from dbo.aud_trade_item
   where trade_num = @trade_num and
         order_num = @order_num and
         item_num = @item_num and
         trans_id <= @asof_trans_id and
	       resp_trans_id > @asof_trans_id
   order by trans_id desc
end
return
GO
GRANT EXECUTE ON  [dbo].[fetchTradeItemRevPK] TO [next_usr]
GO
