SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

CREATE procedure [dbo].[exchangeAutoVouchAccounts] 
as 
set nocount on

-- --------------------------------------------------------
-- SHOWPLAN generated by Peter Lo  9/15/2004
--
--  Table: cost
--    Index : cost_idx3
--      Positioning by key. Keys are: cost_type_code  ASC
--
--  Table: trade_order
--    Index : trade_order_idx1
--    Positioning by key. Keys are: trade_num  ASC
-- --------------------------------------------------------

--   SELECT DISTINCT
--      c.acct_num
--   FROM cost c,
--        trade_order t
--   WHERE c.cost_type_code = 'WAP' AND
--         c.cost_status = 'OPEN' AND
--         c.cost_est_final_ind = 'F' AND
--         t.trade_num = c.cost_owner_key6 AND
--         t.order_num = c.cost_owner_key7 AND
--         t.order_type_code IN ('PHYSBYSL', 'PHYSEXCH')

-- Sempra requested to replace the query above with the following query
--   11/12/2004
   select DISTINCT acct_num 
   from dbo.account_alias 
   where alias_source_code = 'RACK' 
GO
GRANT EXECUTE ON  [dbo].[exchangeAutoVouchAccounts] TO [next_usr]
GO
