CREATE TABLE [dbo].[APPLAUNCHER_CATEGORIES_APPS]
(
[product] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[category_uid] [uniqueidentifier] NOT NULL,
[app_uid] [uniqueidentifier] NOT NULL,
[tile_group] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[position] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[APPLAUNCHER_CATEGORIES_APPS] ADD CONSTRAINT [PK_APPLAUNCHER_CATEGORIES_APPS] PRIMARY KEY CLUSTERED  ([product], [category_uid], [app_uid]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[APPLAUNCHER_CATEGORIES_APPS] TO [next_usr]
GO
GRANT INSERT ON  [dbo].[APPLAUNCHER_CATEGORIES_APPS] TO [next_usr]
GO
GRANT SELECT ON  [dbo].[APPLAUNCHER_CATEGORIES_APPS] TO [next_usr]
GO
GRANT UPDATE ON  [dbo].[APPLAUNCHER_CATEGORIES_APPS] TO [next_usr]
GO
