CREATE TABLE [dbo].[lc_ext_info]
(
[lc_num] [int] NULL,
[red_flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[auto_escalation_ind] [char] (1) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[place_of_payment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[place_of_expiry] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[pay_term_code] [char] (8) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[last_ship_date] [datetime] NULL,
[lc_rate] [float] NULL,
[latest_present_term] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[latest_present_date] [datetime] NULL,
[discount_ind] [char] (1) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[issuing_acct_bank_id] [int] NULL,
[advising_acct_bank_id] [int] NULL,
[confirming_acct_bank_id] [int] NULL,
[guarantee_acct_bank_id] [int] NULL,
[negotiating_acct_bank_id] [int] NULL,
[rate_override_date] [datetime] NULL,
[rate_override_init] [char] (3) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[lc_mod_date] [datetime] NULL,
[lc_mod_init] [char] (3) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[cash_covered_amt] [float] NULL,
[cash_covered_type] [char] (1) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[trans_id] [int] NOT NULL,
[discount_request_ind] [char] (1) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[agreement_date] [datetime] NULL,
[amendment_date] [datetime] NULL,
[amendment_num] [int] NULL,
[comments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[pendingAmendmt_num] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[issuing_bank_limit] [float] NULL,
[paying_agent] [int] NULL
) ON [PRIMARY]
GO
