CREATE TABLE [dbo].[APPLAUNCHER_DASHBOARDS]
(
[filename] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[title] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[description] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[app_uid] [uniqueidentifier] NULL,
[app_keycolumns] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[enabled] [bit] NOT NULL CONSTRAINT [df_APPLAUNCHER_DASHBOARDS_enabled] DEFAULT ((1))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[APPLAUNCHER_DASHBOARDS] ADD CONSTRAINT [PK_APPLAUNCHER_DASHBOARDS] PRIMARY KEY CLUSTERED  ([filename]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[APPLAUNCHER_DASHBOARDS] TO [next_usr]
GO
GRANT INSERT ON  [dbo].[APPLAUNCHER_DASHBOARDS] TO [next_usr]
GO
GRANT SELECT ON  [dbo].[APPLAUNCHER_DASHBOARDS] TO [next_usr]
GO
GRANT UPDATE ON  [dbo].[APPLAUNCHER_DASHBOARDS] TO [next_usr]
GO
