IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'MOH\SYMPHONY_PROD_USERS_RO')
CREATE LOGIN [MOH\SYMPHONY_PROD_USERS_RO] FROM WINDOWS
GO
CREATE USER [MOH\SYMPHONY_PROD_USERS_RO] FOR LOGIN [MOH\SYMPHONY_PROD_USERS_RO]
GO
