IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'MOH\SYMPHONY_PROD_USERS')
CREATE LOGIN [MOH\SYMPHONY_PROD_USERS] FROM WINDOWS
GO
CREATE USER [MOH\SYMPHONY_PROD_USERS] FOR LOGIN [MOH\SYMPHONY_PROD_USERS]
GO
