CREATE SCHEMA [DBMAINT]
AUTHORIZATION [dbo]
GO
GRANT INSERT ON SCHEMA:: [DBMAINT] TO [next_usr]
GO
GRANT SELECT ON SCHEMA:: [DBMAINT] TO [next_usr]
GO
GRANT UPDATE ON SCHEMA:: [DBMAINT] TO [next_usr]
GO
